In [1]:
import sys
print(sys.executable)

C:\Users\deber\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe

In [13]:
import pandas as pd
import csv

In [3]:
with open("weather_data.csv") as data_file:
    data = csv.reader(data_file)
    print(data)
    temperatures = []
    for row in data:
        if row[1] != "temp":
            temperatures.append(int(row[1]))
        print(temperatures)

<_csv.reader object at 0x000002BE4A0905E0>
[]
[12]
[12, 14]
[12, 14, 15]
[12, 14, 15, 14]
[12, 14, 15, 14, 21]
[12, 14, 15, 14, 21, 22]
[12, 14, 15, 14, 21, 22, 24]

In [4]:
data = pandas.read_csv("weather_data.csv")
print(data["temp"])

0    12
1    14
2    15
3    14
4    21
5    22
6    24
Name: temp, dtype: int64

In [5]:
data_dict = data.to_dict()
print(data_dict)

data_list = data["temp"].to_list()
print(data_list)

{'day': {0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'}, 'temp': {0: 12, 1: 14, 2: 15, 3: 14, 4: 21, 5: 22, 6: 24}, 'condition': {0: 'Sunny', 1: 'Rain', 2: 'Rain', 3: 'Cloudy', 4: 'Sunny', 5: 'Sunny', 6: 'Sunny'}}
[12, 14, 15, 14, 21, 22, 24]

In [6]:
average = sum(data["temp"]) / len(data["temp"])

print(average)
print(data["temp"].mean())

print(data["temp"].max())

17.428571428571427
17.428571428571427
24

In [7]:
print(data["condition"])
print(data.condition)

0     Sunny
1      Rain
2      Rain
3    Cloudy
4     Sunny
5     Sunny
6     Sunny
Name: condition, dtype: str
0     Sunny
1      Rain
2      Rain
3    Cloudy
4     Sunny
5     Sunny
6     Sunny
Name: condition, dtype: str

In [8]:
data[data.day == "Monday"]
data[data.temp == data.temp.max()]

monday = data[data.day == "Monday"]
print(monday.condition)

0    Sunny
Name: condition, dtype: str

In [9]:
monday_temp = monday.temp[0]

monday_temp = monday_temp * 9/5 +32

print(monday_temp)

53.6

In [10]:
pandas.DataFrame(data)

         day  temp condition
0     Monday    12     Sunny
1    Tuesday    14      Rain
2  Wednesday    15      Rain
3   Thursday    14    Cloudy
4     Friday    21     Sunny
5   Saturday    22     Sunny
6     Sunday    24     Sunny

In [17]:
data = pandas.read_csv("2018_Central_Park_Squirrel_Census_-_Squirrel_Data_20260914.csv")

In [ ]:
df = pd.DataFrame(data)
df["Primary Fur Color"]
grey_squirrels_count = len(df[df["Primary Fur Color"]=="Gray"])
red_squirrels_count = len(df[df["Primary Fur Color"]=="Cinnamon"])
black_squirrels_count = len(df[df["Primary Fur Color"]=="Black"])
grey_squirrels_count
red_squirrels_count
black_squirrels_count

data_dict = {"Fur color":["Gray","Red","Black"],
             "Count":[grey_squirrels_count,red_squirrels_count,black_squirrels_count]}
data_dict

dict_to_df = pd.DataFrame(data_dict)
dict_to_df

  Fur color  Count
0      Gray   2473
1       Red    392
2     Black    103

: